<?php

return [
    //Engineering Support
    'engineeringSupport' => [
        'warranty_claim_action_create', 'warranty_claim_action_edit', 'warranty_claim_action_show', 'warranty_claim_action_delete', 'warranty_claim_action_access', 'warranty_claim_validation_create', 'warranty_claim_validation_edit', 'warranty_claim_validation_show', 'warranty_claim_validation_delete', 'warranty_claim_validation_access', 'warranty_claim_create', 'warranty_claim_edit', 'warranty_claim_show', 'warranty_claim_delete', 'warranty_claim_access', 'warrantyaction_team_connector_create', 'warrantyaction_team_connector_edit', 'warrantyaction_team_connector_show', 'warrantyaction_team_connector_delete', 'warrantyaction_team_connector_access', 'warranty_claim_remark_create', 'warranty_claim_remark_edit', 'warranty_claim_remark_show', 'warranty_claim_remark_delete', 'warranty_claim_remark_access',
    ],
    //Project Manager
    'projectManager' => [
        'enquiry_show', 'enquiry_access', 'assign_teams_access', 'assign_teams_create', 'equipment_delivery_schedule_create', 'equipment_delivery_schedule_edit', 'equipment_delivery_schedule_show', 'equipment_delivery_schedule_delete', 'equipment_delivery_schedule_access', 'sub_com_installation_access', 'in_house_installation_access', 'installation_progress_access', 'inhouse_installation_team_access', 'sale_contract_approve_access', 'sale_contract_approve_create', 'repair_team_create', 'repair_team_edit', 'repair_team_show', 'repair_team_delete', 'repair_team_access', 'repair_create', 'repair_edit', 'repair_show', 'repair_delete', 'repair_access', 'repair_team_connector_create', 'repair_team_connector_edit', 'repair_team_connector_show', 'repair_team_connector_delete', 'repair_team_connector_access', 'repair_remark_create', 'repair_remark_edit', 'repair_remark_show', 'repair_remark_delete', 'repair_remark_access', 'sale_contract_create', 'sale_contract_edit', 'sale_contract_show', 'sale_contract_delete', 'sale_contract_access', 'sale_contract_pdf_create', 'sale_contract_pdf_edit', 'sale_contract_pdf_show', 'sale_contract_pdf_delete', 'sale_contract_pdf_access', 'sub_com_installation_create', 'sub_com_installation_edit', 'sub_com_installation_show', 'sub_com_installation_delete', 'sub_com_installation_access', 'in_house_installation_create', 'in_house_installation_edit', 'in_house_installation_show', 'in_house_installation_delete', 'in_house_installation_access', 'installation_progress_create', 'installation_progress_edit', 'installation_progress_show', 'installation_progress_delete', 'installation_progress_access', 'inhouse_installation_team_create', 'inhouse_installation_team_edit', 'inhouse_installation_team_show', 'inhouse_installation_team_delete', 'inhouse_installation_team_access', 'on_call_create', 'on_call_edit', 'on_call_show', 'on_call_delete', 'on_call_access', 'warranty_claim_action_create', 'warranty_claim_action_edit', 'warranty_claim_action_show', 'warranty_claim_action_delete', 'warranty_claim_action_access', 'warranty_claim_validation_create', 'warranty_claim_validation_edit', 'warranty_claim_validation_show', 'warranty_claim_validation_delete', 'warranty_claim_validation_access', 'warranty_claim_create', 'warranty_claim_edit', 'warranty_claim_show', 'warranty_claim_delete', 'warranty_claim_access', 'warrantyaction_team_connector_create', 'warrantyaction_team_connector_edit', 'warrantyaction_team_connector_show', 'warrantyaction_team_connector_delete', 'warrantyaction_team_connector_access', 'warranty_claim_remark_create', 'warranty_claim_remark_edit', 'warranty_claim_remark_show', 'warranty_claim_remark_delete', 'warranty_claim_remark_access', 
    ],
    //Service Admin
    'serviceAdmin' => [
        'warranty_claim_action_create', 'warranty_claim_action_edit', 'warranty_claim_action_show', 'warranty_claim_action_delete', 'warranty_claim_action_access', 'warranty_claim_validation_create', 'warranty_claim_validation_edit', 'warranty_claim_validation_show', 'warranty_claim_validation_delete', 'warranty_claim_validation_access', 'warranty_claim_create', 'warranty_claim_edit', 'warranty_claim_show', 'warranty_claim_delete', 'warranty_claim_access', 'warrantyaction_team_connector_create', 'warrantyaction_team_connector_edit', 'warrantyaction_team_connector_show', 'warrantyaction_team_connector_delete', 'warrantyaction_team_connector_access', 'warranty_claim_remark_create', 'warranty_claim_remark_edit', 'warranty_claim_remark_show', 'warranty_claim_remark_delete', 'warranty_claim_remark_access',
        'repair_team_create', 'repair_team_edit', 'repair_team_show', 'repair_team_delete', 'repair_team_access', 'repair_create', 'repair_edit', 'repair_show', 'repair_delete', 'repair_access', 'repair_team_connector_create', 'repair_team_connector_edit', 'repair_team_connector_show', 'repair_team_connector_delete', 'repair_team_connector_access', 'repair_remark_create', 'repair_remark_edit', 'repair_remark_show', 'repair_remark_delete', 'repair_remark_access', 'servicing_team_create', 'servicing_team_edit', 'servicing_team_show', 'servicing_team_delete', 'servicing_team_access', 'servicing_setup_create', 'servicing_setup_edit', 'servicing_setup_show', 'servicing_setup_delete', 'servicing_setup_access', 'servicing_complementary_create', 'servicing_complementary_edit', 'servicing_complementary_show', 'servicing_complementary_delete', 'servicing_complementary_access', 'servicing_contract_create', 'servicing_contract_edit', 'servicing_contract_show', 'servicing_contract_delete', 'servicing_contract_access', 'servicing_team_connector_create', 'servicing_team_connector_edit', 'servicing_team_connector_show', 'servicing_team_connector_delete', 'servicing_team_connector_access', 'servicing_setup_remark_create', 'servicing_setup_remark_edit', 'servicing_setup_remark_show', 'servicing_setup_remark_delete', 'servicing_setup_remark_access', 'on_call_create', 'on_call_edit', 'on_call_show', 'on_call_delete', 'on_call_access', 
    ],
    //Service Manager
    'serviceManager' => [
        'sub_com_installation_create', 'sub_com_installation_edit', 'sub_com_installation_show', 'sub_com_installation_delete', 'sub_com_installation_access', 'in_house_installation_create', 'in_house_installation_edit', 'in_house_installation_show', 'in_house_installation_delete', 'in_house_installation_access', 'installation_progress_create', 'installation_progress_edit', 'installation_progress_show', 'installation_progress_delete', 'installation_progress_access', 'inhouse_installation_team_create', 'inhouse_installation_team_edit', 'inhouse_installation_team_show', 'inhouse_installation_team_delete', 'inhouse_installation_team_access', 'sale_contract_approve_access', 'sale_contract_approve_create', 'repair_team_create', 'repair_team_edit', 'repair_team_show', 'repair_team_delete', 'repair_team_access', 'repair_create', 'repair_edit', 'repair_show', 'repair_delete', 'repair_access', 'repair_team_connector_create', 'repair_team_connector_edit', 'repair_team_connector_show', 'repair_team_connector_delete', 'repair_team_connector_access', 'repair_remark_create', 'repair_remark_edit', 'repair_remark_show', 'repair_remark_delete', 'repair_remark_access', 'servicing_team_create', 'servicing_team_edit', 'servicing_team_show', 'servicing_team_delete', 'servicing_team_access', 'servicing_setup_create', 'servicing_setup_edit', 'servicing_setup_show', 'servicing_setup_delete', 'servicing_setup_access', 'servicing_complementary_create', 'servicing_complementary_edit', 'servicing_complementary_show', 'servicing_complementary_delete', 'servicing_complementary_access', 'servicing_contract_create', 'servicing_contract_edit', 'servicing_contract_show', 'servicing_contract_delete', 'servicing_contract_access', 'servicing_team_connector_create', 'servicing_team_connector_edit', 'servicing_team_connector_show', 'servicing_team_connector_delete', 'servicing_team_connector_access', 'servicing_setup_remark_create', 'servicing_setup_remark_edit', 'servicing_setup_remark_show', 'servicing_setup_remark_delete', 'servicing_setup_remark_access', 'on_call_create', 'on_call_edit', 'on_call_show', 'on_call_delete', 'on_call_access', 'warranty_claim_action_create', 'warranty_claim_action_edit', 'warranty_claim_action_show', 'warranty_claim_action_delete', 'warranty_claim_action_access', 'warranty_claim_validation_create', 'warranty_claim_validation_edit', 'warranty_claim_validation_show', 'warranty_claim_validation_delete', 'warranty_claim_validation_access', 'warranty_claim_create', 'warranty_claim_edit', 'warranty_claim_show', 'warranty_claim_delete', 'warranty_claim_access', 'warrantyaction_team_connector_create', 'warrantyaction_team_connector_edit', 'warrantyaction_team_connector_show', 'warrantyaction_team_connector_delete', 'warrantyaction_team_connector_access', 'warranty_claim_remark_create', 'warranty_claim_remark_edit', 'warranty_claim_remark_show', 'warranty_claim_remark_delete', 'warranty_claim_remark_access', 
    ],
    //Sales Admin
    'salesAdmin' => [
        'enquiry_create', 'enquiry_edit', 'enquiry_show', 'enquiry_delete', 'enquiry_access', 'enquiries_type_create', 'enquiries_type_edit', 'enquiries_type_show', 'enquiries_type_delete', 'enquiries_type_access',
    ],
    //Sales Manager
    'salesManager' => [
        'enquiry_create', 'enquiry_edit', 'enquiry_show', 'enquiry_delete', 'enquiry_access', 'enquiries_type_create', 'enquiries_type_edit', 'enquiries_type_show', 'enquiries_type_delete', 'enquiries_type_access', 'payment_steps_access', 'payment_steps_create', 'equipment_delivery_schedule_create', 'equipment_delivery_schedule_edit', 'equipment_delivery_schedule_show', 'equipment_delivery_schedule_delete', 'equipment_delivery_schedule_access', 'sale_contract_create', 'sale_contract_edit', 'sale_contract_show', 'sale_contract_delete', 'sale_contract_access', 'sale_contract_pdf_create', 'sale_contract_pdf_edit', 'sale_contract_pdf_show', 'sale_contract_pdf_delete', 'sale_contract_pdf_access', 'sale_contract_approve_access', 'sale_contract_approve_create', 
    ],
    //Site Engineer
    'siteEngineer' => [
        'upload_other_docs_create', 'installation_progress_create', 'installation_progress_edit', 'installation_progress_show', 'installation_progress_delete', 'installation_progress_access', 'sub_com_installation_access', 'in_house_installation_access', 'installation_progress_access', 'inhouse_installation_team_access', 'sub_com_installation_create', 'sub_com_installation_edit', 'sub_com_installation_show', 'sub_com_installation_delete', 'sub_com_installation_access', 'in_house_installation_create', 'in_house_installation_edit', 'in_house_installation_show', 'in_house_installation_delete', 'in_house_installation_access', 'installation_progress_create', 'installation_progress_edit', 'installation_progress_show', 'installation_progress_delete', 'installation_progress_access', 'inhouse_installation_team_create', 'inhouse_installation_team_edit', 'inhouse_installation_team_show', 'inhouse_installation_team_delete', 'inhouse_installation_team_access',
    ],
    //Sales Engineer
    'salesEngineer' => [
        'quotation_create', 'quotation_edit', 'quotation_show', 'quotation_delete', 'quotation_access', 'quotation_revision_create', 'quotation_revision_edit', 'quotation_revision_show', 'quotation_revision_delete', 'quotation_revision_access', 'sale_contract_create', 'sale_contract_edit', 'sale_contract_show', 'sale_contract_delete', 'sale_contract_access', 'sale_contract_pdf_create', 'sale_contract_pdf_edit', 'sale_contract_pdf_show', 'sale_contract_pdf_delete', 'sale_contract_pdf_access', 'sale_contract_approve_access', 'sale_contract_approve_create', 'installation_progress_create', 'installation_progress_edit', 'installation_progress_show', 'installation_progress_delete', 'installation_progress_access', 'sub_com_installation_access', 'in_house_installation_access', 'installation_progress_access', 'inhouse_installation_team_access', 'sub_com_installation_create', 'sub_com_installation_edit', 'sub_com_installation_show', 'sub_com_installation_delete', 'sub_com_installation_access', 'in_house_installation_create', 'in_house_installation_edit', 'in_house_installation_show', 'in_house_installation_delete', 'in_house_installation_access', 'installation_progress_create', 'installation_progress_edit', 'installation_progress_show', 'installation_progress_delete', 'installation_progress_access', 'inhouse_installation_team_create', 'inhouse_installation_team_edit', 'inhouse_installation_team_show', 'inhouse_installation_team_delete', 'inhouse_installation_team_access',
    ],
];